### ISSUE TITLE
ipxe error 0x040ee119 when netbooting compute nodes connected only to LAG ports

### ISSUE THREAD

**Issue by SIGUSR2** [joyent/sdcboot#2] opened 2015-11-17 18:44 UTC
When attempting to boot a compute node using nics aggregated on the switch side (Cisco EtherChannel w. LACP), the configuration stage of ipxe will time out with error 0x040ee119. 

The reason appears to be the time it takes an etherchannel-enabled port to move from the "waiting to be aggregated" state to the "Independent" state, during the ipxe part of the boot process. Usually, this means the server will attempt and fail multiple times to boot - randomly managing to boot, but most of the time giving up. 

A quick/tested resolution is:
- add at the end of `src/default.ipxe`: 

```
:retry 
autoboot || goto retry
```
- add in the [GNUmakefile](https://github.com/joyent/sdcboot/blob/master/GNUmakefile#L56) a line with: 

```
EMBED=../../../src/default.ipxe \
```

Without the makefile change, the compiler seems to ignore `default.ipxe` 

With the changes above, the compute node will attempt to boot from the first nic indefinitely. As a side effect, it will have to be configured with the correct PXE-enabled NIC(s) placed first in the boot sequence, or it will never boot.

Please advise if a PR is in order.

**Comment by jclulow** [comment] 2015-11-17 18:57
I have some work in progress on issues related to this behaviour as [HEAD-2269](https://smartos.org/bugview/HEAD-2269).  Are you chainloading iPXE through your legacy PXE boot ROM, or are you loading it from a USB device?

**Comment by SIGUSR2** [comment] 2015-11-17 19:06
Legacy PXE boot ROM. Never tried via USB - but I am 95% sure it will happen the same way, at least in my network environment. The ipxe code performs a reset of the selected nic before attempting to grab an IP from the dhcp server. Because of this reset, Cisco goes through the LACP waiting status again, which is usually longer than the default ipxe dhcp timeout.

**Comment by benjamin-bergia** [comment] 2016-01-21 07:08
I am currently having the exact same issue on CNs connected to an Arista MLAG. 
Tried from legacy PXE and USB, same thing. Funny enough my HN running 20150528 doesn't have the issue.

Other funny thing, only some model of servers are impacted not all of them.
I am in the middle of migration and this is a critical issue for us.

**Comment by jclulow** [comment] 2016-01-21 18:47
@benjamin-bergia As a workaround, can you reduce the convergence time for your MLAG configuration?  How long _is_ the timeout?

**Comment by benjamin-bergia** [comment] 2016-01-22 01:29
@jclulow I am currently working on it.
From [this article](https://eos.arista.com/configuring-lacp-fallback-individual-ports-on-arista-switches) default seems to be 90s.

Apparently servers using QLogic BCM 57800 10GbE cards are not affected. 
Only the servers using the Intel X520-k have issues.

**Comment by jclulow** [comment] 2016-01-22 01:58
So at the moment, when the machine reboots, it will have to wait _90 seconds_ to be able to talk to the network?

**Comment by benjamin-bergia** [comment] 2016-01-22 02:20
That doesn't make any sense, it wouldn't work at all on any of the servers in that case.
I tried to lower the timeout to 3s but it doesn't seem to change anything. 

But yes apparently the default is 90s

**Comment by benjamin-bergia** [comment] 2016-01-22 04:19
I just re-installed my HN using usb-release-20150528-20150528T183354Z-gba7431b-4gb.img

All of my servers boot just fine. It looks like the problem is caused by 13f016db16c2e181c832161f738501f0c42405ba

**Comment by jclulow** [comment] 2016-01-22 04:26
So, I don't _think_ that the problem is caused by 13f016d.  That just includes an extra binary in the `sdcboot` tarball.

It's possible that the move to chainload iPXE instead of `pxegrub` is the problem.  That happened with [NET-322](https://smartos.org/bugview/NET-322).  The ticket for that issue contains some information about how to temporarily use `pxegrub` instead of iPXE via configuration.

You could try that for now, though it's not a long-term fix as maintenance of `pxegrub` has basically stopped and new work is on iPXE.

**Comment by benjamin-bergia** [comment] 2016-01-22 06:08
@jclulow Thank you. I will try with

```
dhcpd_svc=$(sdc-sapi /services?name=dhcpd | json -Ha uuid)
    sapiadm update $dhcpd_svc metadata.chainload_grub=true
```

Is there anything I can do to help ? Do you need any information regarding the NICs or firmwares ?

**Comment by jclulow** [comment] 2016-01-22 06:14
As I recall, when you boot your machine with the regular NIC boot ROM, the iPXE image that is subsequently chainloaded is forced to use the "UNDI only" NIC driver.  This exposes you to potential firmware-related issues.

It would help if you could try booting one of the CNs that is not working from an SDC USB key instead of the onboard NIC boot ROM.  This is our recommended model: all compute nodes in the JPC boot from an SDC USB key which defaults to the `Compute Node (iPXE)` boot option.  This means we can use the real iPXE driver for our NIC and often has more predictable results.

**Comment by benjamin-bergia** [comment] 2016-01-22 06:21
I tried with the USB key but I get the exact same error.

**Comment by jclulow** [comment] 2016-01-22 07:13
It has been quite a while since we've done a resync against upstream iPXE, so I've attempted one of those.  I have a replacement `undionly.kpxe` binary that you can try to see if it helps.  You can download it from:
- https://us-east.manta.joyent.com/jmc/public/ipxe/resync201601/undionly.kpxe

And install it over the top of `/tftpboot/undionly.kpxe` in the `dhcpd0` zone on your headnode.  Subsequent boots (assuming you have not set `chainload_grub=true` yet) should be from the new binary.

**Comment by SIGUSR2** [comment] 2016-01-22 09:45
@jclulow any reason applying the fix I suggested might not be a good idea? I've been using a custom undionly.kpxe binary compiled as described and it works just fine.

**Comment by jclulow** [comment] 2016-01-22 21:54
@SIGUSR2 You mentioned that:

> With the changes above, the compute node will attempt to boot from the first nic indefinitely

I'm not yet convinced that this will avoid breaking existing systems.  I would rather fix whatever bug is causing this.  There are some specific mentions in the iPXE commit history that mention Intel NIC reset behaviour, and either those (or some similar change we could make) might be a better solution here.

**Comment by benjamin-bergia** [comment] 2016-01-25 05:20
@jclulow I added you `undionly.kpxe` file to the dhcp zone. Some of my CNs can now boot, but some of them are still getting the same error. Like @SIGUSR2 explained, we get stuck at the interface configuration step. From the time it takes, the CNs that do actually boot are very close to the timeout of this step. Would it be possible to simply increase the timeout ?

**Comment by jclulow** [comment] 2016-01-25 05:58
@benjamin-bergia Unfortunately there doesn't seem to be an easy way to increase the DHCP timeout in the script that `sdc-booter` sends to the server.  I have compiled another `undionly.kpxe` with a 32 second DHCP timeout (which apparently matches the PXE specification) instead of the default of 10.  Can you try this one?
- https://us-east.manta.joyent.com/jmc/public/ipxe/resync201601/undionly.dhcp32sec.kpxe

**Comment by benjamin-bergia** [comment] 2016-01-25 06:23
@jclulow thanks. It works.
All my CNs boot without issue.

**Comment by benjamin-bergia** [comment] 2016-04-07 04:19
I just upgraded my headnode and platform image to 20160317 and the issue is back. I cannot PXE boot any node anymore. Using a USB key doesn't change anything.

Edit: After looping  multiple times over the NICs, PXE does work but it's pretty random.

**Comment by benjamin-bergia** [comment] 2016-04-07 04:57
I just added your "custom" undionly.kpxe and it works (totally forgot about that). Apparently it didn't make its way to 20160317.

**Comment by Adel-Magebinary** [comment] 2016-05-14 12:34
This issue still occurs in the latest release-20160428-20160428T214653Z-gb176f0e

It will also fail with setting up a compute node with below error. After I ssh into the computenode with pxe boot up with your pxe, the setup scripts are failed. When I cat the joyent_setup script in tmp, it shows 404 not found :-1: 

{
  "execution": "failed",
  "chain_results": [
    {
      "result": "All parameters OK!",
      "error": "",
      "name": "cnapi.validate_params",
      "started_at": "2016-05-14T12:01:17.210Z",
      "finished_at": "2016-05-14T12:01:17.211Z"
    },
    {
      "result": "No nics specified",
      "error": "",
      "name": "napi.validate_nic_params",
      "started_at": "2016-05-14T12:01:17.225Z",
      "finished_at": "2016-05-14T12:01:17.226Z"
    },
    {
      "result": "4 nics retrieved from NAPI",
      "error": "",
      "name": "napi.get_current_nics",
      "started_at": "2016-05-14T12:01:17.240Z",
      "finished_at": "2016-05-14T12:01:17.264Z"
    },
    {
      "result": "No nics to get changes for",
      "error": "",
      "name": "napi.apply_nic_updates",
      "started_at": "2016-05-14T12:01:17.277Z",
      "finished_at": "2016-05-14T12:01:17.278Z"
    },
    {
      "result": "No nics to update",
      "error": "",
      "name": "napi.update_nics",
      "started_at": "2016-05-14T12:01:17.292Z",
      "finished_at": "2016-05-14T12:01:17.293Z"
    },
    {
      "result": "OK",
      "error": "",
      "name": "cnapi.mark_as_setting_up",
      "started_at": "2016-05-14T12:01:17.307Z",
      "finished_at": "2016-05-14T12:01:17.325Z"
    },
    {
      "result": "OK",
      "error": "",
      "name": "cnapi.fetch_setup_files",
      "started_at": "2016-05-14T12:01:17.338Z",
      "finished_at": "2016-05-14T12:01:17.593Z"
    },
    {
      "result": "",
      "error": {
        "message": "Error executing on remote system",
        "statusCode": 500,
        "body": {
          "code": "InternalError",
          "message": "Error executing on remote system"
        },
        "restCode": "InternalError",
        "name": "InternalError"
      },
      "name": "cnapi.execute_joysetup_script",
      "started_at": "2016-05-14T12:01:17.608Z",
      "finished_at": "2016-05-14T12:01:17.734Z"
    }
  ],
  "params": {
    "nic_action": "update",
    "amqp_host": "rabbitmq.MagicLab-Albany01.magiclab.com",
    "cnapi_url": "http://10.1.1.15",
    "assets_url": "http://10.1.1.1",
    "server_uuid": "44454c4c-5300-1032-8042-c8c04f423253",
    "overprovision_ratio": 1,
    "hostname": "MagicLab-ComputeNode01",
    "server_nics": [
      {
        "belongs_to_type": "server",
        "belongs_to_uuid": "44454c4c-5300-1032-8042-c8c04f423253",
        "mac": "d4:be:d9:a8:c4:45",
        "owner_uuid": "930896af-bf8c-48d4-885c-6573a94b1853",
        "primary": false,
        "state": "provisioning"
      },
      {
        "belongs_to_type": "server",
        "belongs_to_uuid": "44454c4c-5300-1032-8042-c8c04f423253",
        "mac": "d4:be:d9:a8:c4:47",
        "owner_uuid": "930896af-bf8c-48d4-885c-6573a94b1853",
        "primary": false,
        "state": "provisioning"
      },
      {
        "belongs_to_type": "server",
        "belongs_to_uuid": "44454c4c-5300-1032-8042-c8c04f423253",
        "mac": "d4:be:d9:a8:c4:49",
        "owner_uuid": "930896af-bf8c-48d4-885c-6573a94b1853",
        "primary": false,
        "state": "provisioning"
      },
      {
        "belongs_to_type": "server",
        "belongs_to_uuid": "44454c4c-5300-1032-8042-c8c04f423253",
        "mac": "d4:be:d9:a8:c4:43",
        "owner_uuid": "930896af-bf8c-48d4-885c-6573a94b1853",
        "primary": false,
        "state": "provisioning",
        "ip": "10.1.1.31",
        "mtu": 1500,
        "netmask": "255.255.255.0",
        "nic_tag": "admin",
        "resolvers": [
          "10.1.1.4"
        ],
        "vlan_id": 0,
        "network_uuid": "6802dbfa-43ac-40ff-a585-86d5598dbe51",
        "nic_tags_provided": [
          "admin"
        ]
      }
    ]
  },
  "server_uuid": "44454c4c-5300-1032-8042-c8c04f423253",
  "target": "44454c4c-5300-1032-8042-c8c04f423253",
  "workflow": "a1211f14-c8ec-450e-b712-2870278faed8",
  "exec_after": null,
  "num_attempts": 0,
  "name": "server-setup-1.0.2",
  "timeout": 7200,
  "max_attempts": 10,
  "workflow_uuid": "a1211f14-c8ec-450e-b712-2870278faed8",
  "created_at": "2016-05-14T12:01:16.551Z",
  "onerror_results": [
    {
      "result": "",
      "error": {
        "name": "Error",
        "message": "Error executing job"
      },
      "name": "onerror",
      "started_at": "2016-05-14T12:01:17.750Z",
      "finished_at": "2016-05-14T12:01:17.751Z"
    }
  ],
  "started": 1463227277210,
  "elapsed": 0.558,
  "uuid": "dc8b70eb-f36e-4ab4-ac60-41d8b251b307",
  "chain": [
    {
      "name": "cnapi.validate_params",
      "timeout": 10,
      "retry": 1,
      "body": "function validateParams(job, callback) {\n    if (!job.params.server_uuid) {\n        callback(new Error('Must specify server_uuid'));\n        return;\n    }\n\n    if (!job.params.cnapi_url) {\n        callback(new Error('Must specify cnapi_url'));\n        return;\n    }\n\n    if (!job.params.assets_url) {\n        callback(new Error('Must specify assets_url'));\n        return;\n    }\n\n    if (!job.params.amqp_host) {\n        callback(new Error('Must specify amqp_host'));\n        return;\n    }\n\n    callback(null, 'All parameters OK!');\n}",
      "uuid": "2525dc89-2217-47f9-9330-53cd16f4ce1a"
    },
    {
      "name": "napi.validate_nic_params",
      "timeout": 10,
      "retry": 1,
      "body": "function validateNicParams(job, callback) {\n    var filtered = [];\n\n    if (!job.params.nics) {\n        return callback(null, 'No nics specified');\n    }\n\n    if (!napiUrl) {\n        callback(new Error('No napiUrl workflow parameter'));\n        return;\n    }\n\n    if ((typeof (job.params.nics) !== 'object') ||\n        !job.params.nics.hasOwnProperty('length')) {\n        return callback(new Error('nics object must be an array'));\n    }\n\n    for (var n in job.params.nics) {\n        var nicObj = job.params.nics[n];\n        if (typeof (nicObj) !== 'object' ||\n            nicObj.hasOwnProperty('length')) {\n            return callback(\n                new Error('nics object must be an array of objects'));\n        }\n\n        if (nicObj.hasOwnProperty('mac') &&\n            nicObj.hasOwnProperty('nic_tags_provided')) {\n            filtered.push({\n                mac: nicObj.mac,\n                nic_tags_provided: nicObj.nic_tags_provided\n            });\n        }\n    }\n\n    job.params.nics = filtered;\n\n    callback(null, 'nic parameters OK!');\n}",
      "uuid": "da4c8d9e-5ac3-4ba7-a2d0-6b5f0ac64f6a"
    },
    {
      "name": "napi.get_current_nics",
      "timeout": 120,
      "retry": 1,
      "body": "function getServerNics(job, callback) {\n    // XXX: if something is set in job.params, return here\n    if (!job.params.server_uuid) {\n        return callback(new Error('No server_uuid specified'));\n    }\n\n    var napi = new sdcClients.NAPI({ url: napiUrl });\n    napi.listNics({ belongs_to_uuid: job.params.server_uuid },\n        function (err, res) {\n        if (err) {\n            job.log.error(err,\n                'error listing server nics for server: '\n                + job.params.server_uuid);\n            return callback(err);\n        }\n\n\n        job.log.debug(res, 'successfully got nics for server: '\n            + job.params.server_uuid);\n        job.params.server_nics = res;\n\n        return callback(null, res.length + ' nics retrieved from NAPI');\n    });\n}",
      "uuid": "b55fa3da-0059-4ad7-a072-884d3cd06509"
    },
    {
      "name": "napi.apply_nic_updates",
      "timeout": 10,
      "retry": 1,
      "body": "function applyNicUpdates(job, callback) {\n    if (!job.params.nics || job.params.nics.length === 0) {\n        return callback(null, 'No nics to get changes for');\n    }\n\n    if (!job.params.nic_action) {\n        return callback(new Error('No nic action specified'));\n    }\n\n    if (job.params.nic_action === 'replace') {\n        return callback(null, 'replacing nic values');\n    }\n\n    if (!job.params.server_nics) {\n        return callback(new Error('No server nics to update'));\n    }\n\n    var oldNics = {};\n    job.params.server_nics.forEach(function (nic) {\n        oldNics[nic.mac] = nic;\n    });\n\n    job.log.debug(oldNics, 'old nics');\n    for (var n in job.params.nics) {\n        var newNic = job.params.nics[n];\n        if (!newNic.hasOwnProperty('mac') ||\n            !oldNics.hasOwnProperty(newNic.mac)) {\n            job.log.warn(newNic, 'missing mac or unknown nic');\n            continue;\n        }\n\n        // Only allow updating nic_tags_provided for now\n        if (!newNic.hasOwnProperty('nic_tags_provided')) {\n            job.log.warn(newNic, 'missing nic_tags_provided');\n            continue;\n        }\n\n        var oldNic = oldNics[newNic.mac];\n\n        if (job.params.nic_action === 'delete') {\n            var afterDeletes = [];\n\n            // No nic tags to begin with, so there's nothing to delete\n            if (!oldNic.nic_tags_provided) {\n                continue;\n            }\n\n            oldNic.nic_tags_provided.forEach(function (tag) {\n                if (newNic.nic_tags_provided.indexOf(tag) === -1) {\n                    afterDeletes.push(tag);\n                }\n            });\n\n            oldNic.nic_tags_provided = afterDeletes;\n            continue;\n        }\n\n        if (job.params.nic_action === 'update') {\n            newNic.nic_tags_provided.forEach(function (tag) {\n                if (!oldNic.nic_tags_provided) {\n                    oldNic.nic_tags_provided = [];\n                }\n\n                if (oldNic.nic_tags_provided.indexOf(tag) === -1) {\n                    oldNic.nic_tags_provided.push(tag);\n                }\n            });\n        }\n    }\n\n    var newNicParams = [];\n    for (var o in oldNics) {\n        newNicParams.push({\n            mac: o,\n            nic_tags_provided: oldNics[o].nic_tags_provided\n        });\n    }\n\n    var msg = 'applied nic ' + job.params.nic_action + 's';\n    job.log.info(newNicParams, msg);\n    job.params.nics = newNicParams;\n    return callback(null, msg);\n}",
      "uuid": "455d6ad8-8eec-470c-9ef5-2a2d059e1a88"
    },
    {
      "name": "napi.update_nics",
      "timeout": 120,
      "retry": 1,
      "body": "function updateNics(job, callback) {\n    if (!job.params.nics || job.params.nics.length === 0) {\n        return callback(null, 'No nics to update');\n    }\n\n    var napi = new sdcClients.NAPI({ url: napiUrl });\n    return async.forEach(job.params.nics, function (nic, cb) {\n        var mac = nic.mac;\n        napi.updateNic(mac, nic, function (err, res) {\n            if (err) {\n                job.log.error(err, 'error updating nic: ' + mac);\n                return cb(err);\n            }\n\n            job.log.debug(res, 'successfully updated nic: ' + mac);\n            return cb();\n        });\n    }, function (err) {\n        if (err) {\n            return callback(err);\n        }\n\n        return callback(null, 'nics updated in NAPI successfully');\n    });\n}",
      "uuid": "ac7a51b2-534e-460d-8b35-d83cea9b446c"
    },
    {
      "name": "cnapi.mark_as_setting_up",
      "timeout": 10,
      "retry": 1,
      "body": "function markServerAsSettingUp(job, callback) {\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n    var serverUrl = '/servers/' + job.params.server_uuid;\n\n    var payload = {\n        setting_up: true\n    };\n\n    cnapi.post(serverUrl, payload, function (error, req, res) {\n        if (error) {\n            job.log.info('Error setting server as setting_up');\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "928fd79a-629e-4553-a817-9fe6d1519ce3"
    },
    {
      "name": "cnapi.fetch_setup_files",
      "timeout": 10,
      "retry": 1,
      "body": "function fetchSetupFiles(job, callback) {\n    var urUrl = '/servers/' + job.params.server_uuid + '/execute';\n    var cnapiUrl = job.params.cnapi_url;\n    var assetsUrl = job.params.assets_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n    var overprovision_ratio = job.params.overprovision_ratio || '1.0';\n    var nodeConfigDir = 'config-' + job.params.server_uuid;\n\n    var script = [\n        '#!/bin/bash',\n        'set -o xtrace',\n        'cd /var/tmp',\n        'mkdir /var/tmp/node.config',\n        'mkdir /var/tmp/' + nodeConfigDir,\n        '(echo \"overprovision_ratio=\\'' + overprovision_ratio + '\\'\"; '\n            + 'curl $1/extra/joysetup/node.config) | tee ' + nodeConfigDir +\n              '/node.config node.config/node.config >&-',\n        'curl -O $1/extra/joysetup/joysetup.sh',\n        'curl -O $1/extra/joysetup/agentsetup.sh',\n        'chmod +x *.sh'\n    ].join('\\n');\n\n    var payload = {\n        script: script,\n        args: [assetsUrl]\n    };\n\n    cnapi.post(urUrl, payload, function (error, req, res) {\n        if (error) {\n            job.log.info('Error executing joysetup: ' + error.message);\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "8f331d5e-df8c-47c3-9bda-2aecc29740dc"
    },
    {
      "name": "cnapi.execute_joysetup_script",
      "timeout": 3600,
      "retry": 1,
      "body": "function executeJoysetupScript(job, callback) {\n    var urUrl = '/servers/' + job.params.server_uuid + '/execute';\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n\n    var script = [\n        '#!/bin/bash',\n        'set -o xtrace',\n        'cd /var/tmp',\n        './joysetup.sh'\n    ].join('\\n');\n\n    var payload = {\n        script: script\n    };\n\n    cnapi.post(urUrl, payload, function (error, req, res) {\n        if (error) {\n            job.log.info('Error executing joysetup: ' + error.message);\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        job.log.info('Successfully executed joysetup script');\n        callback();\n    });\n}",
      "uuid": "4990ffa8-63c9-428e-ad89-cc0f48f6e97c"
    },
    {
      "name": "cnapi.execute_agentsetup_script",
      "timeout": 3600,
      "retry": 1,
      "body": "function executeAgentSetupScript(job, callback) {\n    var urUrl = '/servers/' + job.params.server_uuid + '/execute';\n    var cnapiUrl = job.params.cnapi_url;\n    var assetsUrl = job.params.assets_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n\n    var script = [\n        '#!/bin/bash',\n        'set -o xtrace',\n        'cd /var/tmp',\n        'echo ASSETS_URL = $ASSETS_URL',\n        './agentsetup.sh'\n    ].join('\\n');\n\n    var payload = {\n        script: script,\n        env: { ASSETS_URL: assetsUrl }\n    };\n\n    cnapi.post(urUrl, payload, function (error, req, res) {\n        if (error) {\n            job.log.info('Error executing agent setup via CNAPI:'\n                + error.message);\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "8b095074-70d0-4a86-a4df-09c625edf559"
    },
    {
      "name": "cnapi.update_nics",
      "timeout": 3600,
      "retry": 1,
      "body": "function nicUpdate(job, callback) {\n        if (!job.params.nics || job.params.nics.length === 0) {\n            return callback(null, 'No nics to update');\n        }\n\n        var cnapi = new sdcClients.CNAPI({ url: cnapiUrl });\n        var endpoint = '/servers/' + job.params.server_uuid + '/nics/update';\n        job.params.taskIDs = [];\n\n        job.log.debug(job.params.nics, 'Updating rules on server \"%s\"',\n            job.params.server_uuid);\n\n        return cnapi.post(endpoint, { nics: job.params.nics },\n            function (err, task) {\n            if (err) {\n                return callback(err);\n            }\n\n            job.log.debug(task, 'Server \"%s\": nic update task \"%s\"',\n                job.params.server_uuid, task.id);\n            job.params.taskIDs.push({ server_uuid: job.params.server_uuid,\n                task_id: task.id});\n            return callback(null, 'Started nic update task on server');\n        });\n}",
      "uuid": "cfc6f40c-14ec-4a97-aa9c-f74b616aa336"
    },
    {
      "name": "cnapi.poll_tasks",
      "timeout": 3600,
      "retry": 1,
      "body": "function pollTasks(job, callback) {\n    if (!job.params.taskIDs || job.params.taskIDs.length === 0) {\n        return callback(null, 'No tasks to poll');\n    }\n\n    var cnapi = new sdcClients.CNAPI({ url: cnapiUrl });\n\n    job.params.taskSuccesses = [];\n    job.params.taskFailures = [];\n\n    return async.forEach(job.params.taskIDs, function (detail, cb) {\n        var timeout = null;\n\n        function pollOne() {\n            cnapi.getTask(detail.task_id, function onCnapi(err, task) {\n                if (timeout) {\n                    clearTimeout(timeout);\n                }\n\n                if (err) {\n                    return cb(err);\n                }\n\n                job.log.debug(task, 'retrieved task for server \"%s\"',\n                    detail.server_uuid);\n                if (task.status == 'failure') {\n                    job.params.taskFailures.push(detail);\n                    return cb(new Error('CNAPI task \"' + detail.task_id\n                        + '\" failed for server \"' + detail.server_uuid + '\"'));\n                }\n\n                if (task.status == 'complete') {\n                    job.params.taskSuccesses.push(detail);\n                    return cb(null);\n                }\n\n                timeout = setTimeout(pollOne, 1000);\n            });\n        }\n\n        pollOne();\n    }, function (err) {\n        if (err) {\n            return callback(err);\n        }\n\n        return callback(null, 'All server tasks returned successfully');\n    });\n}",
      "uuid": "ab7d586a-2eb1-4c34-bbd0-8e7a463140ea"
    },
    {
      "name": "cnapi.touch_setup_complete",
      "timeout": 1000,
      "retry": 1,
      "body": "function touchSetupComplete(job, callback) {\n    var urUrl = '/servers/' + job.params.server_uuid + '/execute';\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n\n    var script = [\n        '#!/bin/bash',\n        'touch /var/svc/setup_complete'\n    ].join('\\n');\n\n    var payload = {\n        script: script\n    };\n\n    cnapi.post(urUrl, payload, function (error, req, res) {\n        if (error) {\n            job.log.info('Error posting to Ur via CNAPI:' + error.message);\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "ff640702-5cd0-44a4-9963-d74ae84ffa09"
    },
    {
      "name": "cnapi.refresh_server_sysinfo",
      "timeout": 1000,
      "retry": 1,
      "body": "function refreshServerSysinfo(job, callback) {\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n    var serverUrl = '/servers/' + job.params.server_uuid + '/sysinfo-refresh';\n\n    cnapi.post(serverUrl, {}, function (error, req, res) {\n        if (error) {\n            job.log.info('Error refreshing server sysinfo');\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "54ff668e-2e59-449f-a8b0-9c7f946b2460"
    },
    {
      "name": "cnapi.reboot_server",
      "timeout": 600,
      "retry": 1,
      "body": "function rebootServer(job, callback) {\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n    var urUrl = '/servers/' + job.params.server_uuid + '/execute';\n\n    var payload = {\n        script: '#!/bin/bash\\nexit 113'\n    };\n\n    job.log.info('rebootServer');\n\n    if (!job.params.hostname) {\n        job.log.info('No need to reboot, hostname not set');\n        callback();\n        return;\n    }\n\n    cnapi.post(urUrl, payload, function (error, req, res) {\n        job.log.info('rebootServer (post)');\n        if (error) {\n            job.log.info('Error posting to Ur via CNAPI:' + error.message);\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "7fe9310d-7783-496c-89cd-68ef23450596"
    },
    {
      "name": "cnapi.wait_for_reboot",
      "timeout": 1200,
      "retry": 1,
      "body": "function waitForReboot(job, callback) {\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n    var timer;\n    var serverUrl = '/servers/' + job.params.server_uuid;\n\n    job.log.info('waitForReboot()');\n\n    if (!job.params.hostname) {\n        job.log.info('No need to wait for reboot, hostname not set');\n        callback();\n        return;\n    }\n\n    function checkRebooted() {\n        cnapi.get(serverUrl, function (err, req, res, server) {\n            var cn_state;\n            var created_at;\n            var last_boot;\n\n            if (err) {\n                job.log.info(\n                    'Error getting server info from CNAPI:' + err.message);\n                job.log.info(err.stack.toString());\n                clearTimeout(timer);\n                callback(err);\n                return;\n            }\n\n            job.log.info('waitForReboot() got result from CNAPI');\n\n            cn_state = server.status;\n            job.log.info('cn_state: ' + cn_state);\n            created_at = (new Date(job.created_at).getTime() / 1000);\n            job.log.info('created_at: ' + created_at);\n            last_boot = (new Date(server.last_boot).getTime() / 1000);\n            job.log.info('last_boot: ' + last_boot);\n\n            if (cn_state === 'running' && (last_boot > created_at)) {\n                clearTimeout(timer);\n                callback();\n                return;\n            }\n            timer = setTimeout(checkRebooted, 5000);\n        });\n    }\n\n    timer = setTimeout(checkRebooted, 5000);\n}",
      "uuid": "ee8f01a1-a25e-47bf-a137-aa7ca4f5d89b"
    },
    {
      "name": "cnapi.run_postsetup_script",
      "timeout": 1000,
      "retry": 1,
      "body": "function runPostSetupScript(job, callback) {\n    var urUrl = '/servers/' + job.params.server_uuid + '/execute';\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n\n    if (!job.params.postsetup_script) {\n        callback();\n        return;\n    }\n\n    var payload = {\n        script: job.params.postsetup_script\n    };\n\n    cnapi.post(urUrl, payload, function (error, req, res) {\n        if (error) {\n            job.log.info('Error posting to Ur via CNAPI:' + error.message);\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "ab6f04c8-0d79-4a1e-a43a-eab30716ab78"
    },
    {
      "name": "cnapi.restart_ur",
      "timeout": 1000,
      "retry": 1,
      "body": "function restartUr(job, callback) {\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n    var urUrl = '/servers/' + job.params.server_uuid + '/execute';\n\n    var payload = {\n        script:\n            '#!/bin/bash\\n'+\n            'nohup /bin/bash -c ' +\n                '\"(/usr/bin/sleep 5; /usr/sbin/svcadm restart ur) &\"'\n    };\n\n    job.log.info('restartUr');\n\n    cnapi.post(urUrl, payload, function (error, req, res) {\n        job.log.info('restartUr (post)');\n        if (error) {\n            job.log.info('Error posting to Ur via CNAPI:' + error.message);\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "26bd0212-b402-463e-ab9a-9cc6ada96c21"
    },
    {
      "name": "cnapi.mark_server_as_setup",
      "timeout": 1000,
      "retry": 1,
      "body": "function markServerAsSetup(job, callback) {\n    var cnapiUrl = job.params.cnapi_url;\n    var cnapi = restify.createJsonClient({ url: cnapiUrl});\n    var serverUrl = '/servers/' + job.params.server_uuid;\n\n    var payload = {\n        setup: true,\n        setting_up: false\n    };\n\n    cnapi.post(serverUrl, payload, function (error, req, res) {\n        if (error) {\n            job.log.info('Error setting server as setup');\n            job.log.info(error.stack.toString());\n            callback(error);\n            return;\n        }\n        callback();\n    });\n}",
      "uuid": "74631fa4-5451-41ca-b0ed-7299455f7016"
    }
  ],
  "onerror": [
    {
      "name": "onerror",
      "body": "function (job, cb) {\n                cb(new Error('Error executing job'));\n            }",
      "uuid": "507a321d-f080-482a-bb00-7e0a85aa5613"
    }
  ]
}

**Comment by Adel-Magebinary** [comment] 2016-07-12 04:07
This hasn't made its way to 20160707 too. Can someone please merge the pxe in?

**Comment by Adel-Magebinary** [comment] 2016-09-14 21:20
@jclulow can we please add the longer time out pxe to the next release? I upgraded headnode & CNs and CNs don't boot up because of DHCP timeout. making it a huge problem for us.

**Comment by jclulow** [comment] 2016-09-15 09:29
@Adel-Magebinary I spent some time on this today, via [HEAD-2321](https://smartos.org/bugview/HEAD-2321).  I'll let you know the final verdict, but I'm hoping it will be in the next release!

**Comment by jclulow** [comment] 2016-09-16 21:58
The fix for HEAD-2321 was included in the latest release.  The default DHCP timeout is now 32 seconds instead of 10.

For users booting from their legacy PXE ROM, to chainload iPXE from the Triton PXE server, you'll want to make sure you update:

```
# sdcadm self-update --latest
# sdcadm update dhcpd
```

If, instead, you are booting your compute nodes from the copy of iPXE on the Triton USB key image, you'll want to make sure those are updated with the new version:

```
# sdcadm self-update --latest
# sdcadm experimental update-gz-tools --latest
```

**Closed as completed by jclulow** 2016-09-16 21:58 UTC
